---

- name: Install logwatch
  action: apt pkg=logwatch state=installed

- name: Make logwatch mail $logwatch_email daily
  action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto $logwatch_email --detail high" state=present create=yes
