---

- name: Install php
  apt: package={{ item }} state=present
  with_items:
    - php5
    - php5-cli
    - php5-json
    - php5-mysql
    - php5-curl
    - php5-mcrypt
    - php5-gd
    - php5-imagick
    - php5-fpm

# Ubuntu 13.10 has a bug in where the mcrypt ini file is placed.
# Work around those by copying the file to the proper location and enabling mcrypt.
- name: Copy mcrypt ini to proper location and enable
  shell: cp /etc/php5/conf.d/mcrypt.ini /etc/php5/mods-available/mcrypt.ini && php5enmod mcrypt creates=/etc/php5/mods-available/mcrypt.ini
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'saucy'
  notify:
    - restart php-fpm

- name: Remove default php-fpm pool
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  notify:
    - restart php-fpm

- name: Create php-fpm log directory
  file: path=/var/log/php-fpm state=directory owner=www-data

- name: Create php log directory
  file: path=/etc/log/php state=directory owner=www-data

- name: Create php upload directory
  file: path=/etc/lib/php/upload state=directory owner=www-data

- name: Create php session directory
  file: path=/etc/lib/php/session state=directory owner=www-data

- name: Modify php.ini settings
  copy: src=templates/php.ini dest=/etc/php5/fpm/php.ini
  notify:
    - restart php-fpm
